### ISSUE TITLE
U+2019 closing quote does delimit end markup strings

### ISSUE THREAD

**Issue by anntzer** [marshallward/vim-restructuredtext#1]
Woohoo, let's inaugurate this bug tracker!

Briefly
```
    `foo`’s
```
is a proper RST string consisting of the "foo" interpreted text block followed by the U+2019 RIGHT SINGLE QUOTATION MARK / `'9` digraph, and then the character "s".

This is not recognized by the current `syntax/rst.vim`, which just lets the interpreted text block continue running after that (basically because U+2019 is not added as a separator in `DefineOneInlineMarkup`).

This is specified by point 4c of the spec (http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#inline-markup-recognition-rules), and correctly recognized by Sphinx.

Use case (yes, it's not just to annoy you :-)):
Sometimes I'd like to write, e.g.
```
    A `Widget`'s parent does etc.
```
(where `Widget` is a reference to a class name).  Unfortunately, smartypants misguesses that the single quote is a *left* (opening) quote, not a *right* (closing) quote.  Using U+2019 directly in the source prevents this issue.

**Comment by marshallward** [comment]
Yikes, I don't even think the repo version is up to date!

Yeah, I can reproduce this.  I'll take your word that it's valid Sphinx output, and the standard seems more or less clear on the issue of non-alphanumeric characters.

I've got a fix for this, and I'll update it tomorrow when I get into work.

**Comment by marshallward** [comment]
I just pushed a change that adds support for U+2019, but it's clear from the doc you linked that there are a lot of other characters that ought to be supported.  But I'll think I'll leave those out until requested, some of them are pretty exotic.

Anyway, thanks very much for the update!

**Comment by anntzer** [comment]
Yup, I agree general support is probably overkill...  I'll just keep raising bugs whenever I come up with reasonable other characters to support :-)
Or another option may be to add some `g:rst_extra_markup_delimiters` (or so) variable that let's the user add his own quotation marks that he needs to support?

**Comment by marshallward** [comment]
thanks good idea, I'll close this one and move that to a Feature issue
