### ISSUE TITLE
No Spell Check on rst Section Headings

### ISSUE THREAD

**Issue by markperfectsensedigital** [marshallward/vim-restructuredtext#10]
Thanks for making the VIM rST syntax highlighter. Works perfectly.

Currently VIM does not do spell check on rST headings, and seems like a reasonable design decision. Can you add 
a) an instruction in rst.vim explaining how to turn on spell check for rST headings?
b) add commented-out lines that turn on such spelling?

Thank you.

**Comment by marshallward** [comment]
Thanks, I think this is a good idea.  I've explicitly added `contains=@Spell` to the section highlight.

Maybe there's a more elegant solution, such as a flag to enable it, but I think having it on all the time is generally reasonable.
