### ISSUE TITLE
`::` sometimes misinterpreted as underlining section title when it actually introduces a literal block

### ISSUE THREAD

**Issue by anntzer** [marshallward/vim-restructuredtext#13]
In
```
A
::

   foo

AB
::

   bar

ABC
::

   baz
```
vim-restructuredtext highlights `A`, `AB` and `ABC` all as section headers, when in fact the third one (or longer strings) should be considered as normal text, and the `::` introduces a code block (which should, likewise, be highlighted as such -- this is not the case right now).  You can check with `rst2html`.  The spec (http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#sections) says
> Sections are identified through their titles, which are marked up with adornment: "underlines" below the title text, or underlines and matching "overlines" above the title. An underline/overline is a single repeated punctuation character that begins in column 1 and forms a line *extending at least as far as the right edge of the title text*.

(emphasis mine).

Such a case occurs in practice when one wants introduce a code block without having a colon at the end of the previous paragraph, e.g.
```
... this is the end of the previous paragraph.
::
   some literal stuff
```

(yes, one could also just add an extra newline before the `::`)

**Comment by marshallward** [comment]
Good spotting, I agree this should be fixed.

Counting prior string lengths is a bit beyond my vimscript ability, so this might need to invest some time into this.  I'm on holiday this month, but I'll try to look into it when I get back.
