### ISSUE TITLE
There is a setting example that causes an error in ":h rst.vim"

### ISSUE THREAD

**Issue by yaegassy** [marshallward/vim-restructuredtext#46]
Hi,

Are you `:h rst.vim` maintainer?

There is a setting example that causes an error in `:h rst.vim`.

https://github.com/vim/vim/blob/master/runtime/doc/syntax.txt#L2772-L2777

### Current

```vim
    let rst_syntax_code_list = {
        \ 'cpp' = ['cpp', 'c++'],
        \ 'bash' = ['bash', 'sh'],
        ...
	}
```

### Change

I think it would be better to change this way.

```vim
    let g:rst_syntax_code_list = {
        \ 'cpp':  ['cpp', 'c++'],
        \ 'bash': ['bash', 'sh'],
        ...
        \ }
```

**Comment by marshallward** [comment]
Sure, that seems fine.  I don't maintain the vim docs, so if you want to send a patch to the main vim repo then that might be easiest.

**Comment by yaegassy** [comment]
Since `vim-restructuredtext` is buitin with Vim, I misunderstood it.

If you look at the header of the syntax.txt file, is Bram the maintainer?

I'm sorry, can you ask me to fix it if possible?

**Comment by marshallward** [comment]
No worries, your confusion is understandable :).  I don't mind making the change, I'll send it right now.

**Comment by marshallward** [comment]
PR is here: https://github.com/vim/vim/pull/5249

**Comment by yaegassy** [comment]
Thanks!
