### ISSUE TITLE
rstHyperlinkReference performance-killer when rstInlineLiteral has underscores

### ISSUE THREAD

**Issue by smackesey** [marshallward/vim-restructuredtext#51]
Using `rstInlineLiteral` items that include underscores causes near-unusable performance issues when the file reaches a certain size. Below is a sample file that will replicate this issue. Open this file, `set filetype=rst`, place the cursor at the bottom, and start typing. Using `syntime` gives results like this:

```
0.39622 rstHyperlinkReference
0.005879 rstInlineInternalTargets
...
```

Notice the order of magnitude difference between the top item, `rstHyperlinkReference`, and everything else. This disappears if the underscores in between the "`" are deleted or escaped with a "\\".

While the lag for this particular file isn't too bad on my machine, I see the same issue with much worse lag in other files. The one I posted was just the simplest one I could invent to replicate the issue.

[testrst.txt](https://github.com/marshallward/vim-restructuredtext/files/4278591/testrst.txt)

**Comment by marshallward** [comment]
I'm not seeing anything like this.  `rstHyperlinkReference` is the highest cost, but it's comparable to `rstInlineInternalTargets`.

Are you using the builtin rst.vim syntax file, or the one in this repository?  I tried both and did not see a big difference, but at least we should start from the same version.

**Comment by marshallward** [comment]
It's a bit random to show this, but just as a reference point, this was my log:
```
  TOTAL      COUNT  MATCH   SLOWEST     AVERAGE   NAME               PATTERN
  0.007652   288    0       0.000058    0.000027  rstHyperlinkReference \<[[:alnum:]]\%([-_.:+]\?[[:alnum:]]\+\)*__\=\ze\%($\|\s\|['")\]}>/:.,;!?\\-]\)
  0.006861   288    0       0.000051    0.000024  rstInlineInternalTargets \%(^\|\s\|\%ua0\|['"([{</:]\)\zs_`[^[:space:]`] `\ze\%($\|\s\|['")\]}>/:.,;!?\\-]\)
  0.006735   288    0       0.000055    0.000023  rstStrongEmphasis  \%(^\|\s\|\%ua0\|['"([{</:]\)\zs\*\*[^[:space:]*] \*\*\ze\%($\|\s\|['")\]}>/:.,;!?\\-]\)
  0.006722   288    0       0.000049    0.000023  rstEmphasis        \%(^\|\s\|\%ua0\|['"([{</:]\)\zs\*[^[:space:]*] \*\ze\%($\|\s\|['")\]}>/:.,;!?\\-]\)
  0.006697   288    0       0.000053    0.000023  rstInlineLiteral   \%(^\|\s\|\%ua0\|['"([{</:]\)\zs``[^[:space:]`] ``\ze\%($\|\s\|['")\]}>/:.,;!?\\-]\)
  0.006683   288    0       0.000059    0.000023  rstSubstitutionReference \%(^\|\s\|\%ua0\|['"([{</:]\)\zs|[^[:space:]|] |_\{0,2}\ze\%($\|\s\|['")\]}>/:.,;!?\\-]\)
  0.006681   288    0       0.000057    0.000023  rstInterpretedTextOrHyperlinkReference \%(^\|\s\|\%ua0\|['"([{</:]\)\zs`[^[:space:]`] `_\{0,2}\ze\%($\|\s\|['")\]}>/:.,;!
?\\-]\)
  0.005593   288    0       0.000046    0.000019  rstInlineInternalTargets \%(^\|\s\|\%ua0\|[/:]\)\zs_`\ze[^[:space:]`]
  0.005567   288    0       0.000048    0.000019  rstSubstitutionReference \%(^\|\s\|\%ua0\|[/:]\)\zs|\ze[^[:space:]|]
```
My logs with and without the underscores were more or less identical.  All I did was type `test` on four lines at the end of the file.

**Comment by smackesey** [comment]
@marshallward Thanks for your prompt attention to this!

    Are you using the builtin rst.vim syntax file, or the one in this repository?

I am using the builtin rst.vim syntax file from Vim 8.1.2234 (MacVim).

The issue is tricky as the degree of lag seems to vary a lot depending on the file contents and where you are typing. I've noticed that the lag is not actually so bad typing at the end of the file.

Instead of typing four lines of "test" at the end, try typing four lines of "test" in between the "Section 4" header and the final paragraph. I've just run this experiment several times and consistently gotten results like this:

0.026490 rstHyperlinkReference
0.004082 rstInlineInternalTargets

This is particularly strange since the typed-in text doesn't have any hyperlink references.

(Sorry for not posting the full syntime table rows, I'm not sure how to copy them though from MacVim).

**Comment by marshallward** [comment]
Current Vim is 8.2.x and the version in the repository is even newer, and we did sort out some performance issues since 8.1, so you may find that this is a problem that's been solved already.  Can you try the version in this repository and see if you observe the problem?

(If you haven't done this before, then you can put `syntax/rst.vim` in your `.vim/syntax` file in `$HOME`.)

I will also try to identify which version is in Vim 8.1 and see if I can reproduce your problem.

**Comment by smackesey** [comment]
@marshallward OK, I updated to Vim 8.2. My apologies for using an older version-- was using the latest MacVim, but this apparently lags core vim by quite a bit, MacVim just updated to 8.2 a few days ago. Repeating the above experiment (4 lines of "test" under the Section 4 header) now gives:

    0.002784 rstHyperlinkReference
    0.002584 rstEmphasis

As the first two lines. That's an order of magnitude performance in `rstHyperlinkReference`, so it really looks like something significant changed between the versions to fix the problem. I've also been editing other RST files for a few days and haven't observed the issue. So I will close and assume it is fixed. Thank you!

**Comment by marshallward** [comment]
No worries, we started to notice some performance issues a while back and have only started trying to understand and get them under control, so I'm glad we seem to be in the right direction.

I also owe you a thanks for introducing me to `syntime`.  I was previously using some very inefficient methods for timing these things.  Thanks!
