### ISSUE TITLE
Empty role followed by "." not highlighted correctly

### ISSUE THREAD

**Issue by smackesey** [marshallward/vim-restructuredtext#52]
<img width="597" alt="highlight" src="https://user-images.githubusercontent.com/1531373/76869233-3d50b700-6825-11ea-99c2-ce0ab1624949.png">

Observe that the empty `:test:` role, when followed by `.`, causes the following text to be highlighted. It appears that the "\`\`" is being interpreted as the opening delimiter for an `rstInlineLiteral` when it should be treated as empty delimiters for `rstInterpretedTextOrHyperlinkReference`.

**Comment by marshallward** [comment]
Agreed, this looks like a bug.  We probably need to require the first character not be a space.

**Comment by marshallward** [comment]
I just tested this in `rst2html` and it seems like the syntax highlight matches the HTML output.  Does yours look different?

**Comment by smackesey** [comment]
Yes, I tried the same and got output that does not match what I expect. I went looking in the restructuredtext docs for any mention of "empty" roles,  but couldn't find anything. I had assumed empty roles were supported in restructuredText, but it appears they're not. So closing, thanks for looking it into it anyway.
