### ISSUE TITLE
substitution references may contain spaces

### ISSUE THREAD

**Issue by anntzer** [marshallward/vim-restructuredtext#9]
The following example is from http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#substitution-definitions:

```
|The Transparent Society| offers a fascinating alternate view
on privacy issues.

.. |The Transparent Society| book:: isbn=0738201448
```

rst.vim currently does not highlight `.. |The Transparent Society|` as a reference due to the presence of spaces.

**Comment by marshallward** [comment]
Yeah, confirmed.  Looks like `rstSubstitutionDefinition` is borrowing the rules for single-word references.  Thanks for finding it.

**Comment by marshallward** [comment]
This should be fixed now.  I've introduced a `PhraseReference` definition alongside the single-word `ReferencePhrase`.  Can you try it out?

**Comment by anntzer** [comment]
Works for me, thanks!

**Comment by anntzer** [comment]
Actually, substitution references may simply contain any character (vertical bars must be escaped of course) (http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#inline-markup).  Thus, while I didn't find this explicitly in the text, it is reasonable to believe that their definitions may also contain arbitrary text.

See https://raw.githubusercontent.com/anntzer/mplcursors/master/README.rst /https://github.com/anntzer/mplcursors/blob/master/README.rst (the gitter link) for a real-life example, which indicates that this is indeed docutils' behavior.

Accordingly, can you reopen the issue?  Thanks in advance.

I guess it may be possible to hack Define{,One}InlineMarkup to make the make the defined group optionally contained, but I haven't been successful trying that.

**Comment by marshallward** [comment]
Maybe just wildcard the whole thing then?  (Maybe also redefine as a region with a `skip` for escaped `|` ?)

Something like this:

    execute 'syn match rstSubstitutionDefinition contained' .
      \ ' /|.*|\_s\+/ nextgroup=@rstDirectives'

**Comment by anntzer** [comment]
No strong opinion as to the best way to implement this.

**Comment by marshallward** [comment]
I'll do the wildcard for now, and wait for the inevitable problems to emerge :)

**Comment by marshallward** [comment]
Changed in 6da8601 will close if it all looks good.

**Comment by anntzer** [comment]
Well, looks good enough for until next time I find something :-)
